### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by sega16322** [sega16322/chat-space#11]
＃IPアドレス
3.114.203.18

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・4箇所の背景色をカリキュラムの指定どおりにしましょう！
<img width="716" alt="スクリーンショット 2020-04-07 11 11 28" src="https://user-images.githubusercontent.com/49669977/78622641-9e1d5d80-78c0-11ea-8ab9-d31a7fea9197.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
